#!/usr/bin/env python3
"""Setup script for Supabase database configuration."""

import asyncio
import os
from urllib.parse import urlparse

from crawler.db_repository import DatabaseRepository


def get_supabase_info():
    """Get Supabase connection information from user."""
    print("🚀 Supabase Setup for GitHub Crawler")
    print("=" * 50)
    print()
    print("You'll need your Supabase connection details.")
    print("Find them in: Supabase Dashboard → Settings → Database → Connection Info")
    print()

    # Option 1: Connection URL (recommended)
    print("Option 1: Use Connection URL (recommended)")
    connection_url = input("Enter your Supabase DATABASE_URL (or press Enter to skip): ").strip()

    if connection_url:
        # Parse the URL to validate and show details
        try:
            parsed = urlparse(connection_url)
            print("✅ Parsed connection:")
            print(f"   Host: {parsed.hostname}")
            print(f"   Database: {parsed.path[1:] if parsed.path else 'N/A'}")
            print(f"   User: {parsed.username}")
            return {"DATABASE_URL": connection_url}
        except Exception as e:
            print(f"❌ Invalid URL format: {e}")
            return None

    # Option 2: Individual parameters
    print("\nOption 2: Enter individual connection details")

    host = input("Host (e.g., db.xxx.supabase.co): ").strip()
    if not host:
        print("❌ Host is required")
        return None

    port = input("Port [5432]: ").strip() or "5432"
    database = input("Database name [postgres]: ").strip() or "postgres"
    user = input("User [postgres]: ").strip() or "postgres"
    password = input("Password: ").strip()

    if not password:
        print("❌ Password is required")
        return None

    return {
        "POSTGRES_HOST": host,
        "POSTGRES_PORT": port,
        "POSTGRES_DB": database,
        "POSTGRES_USER": user,
        "POSTGRES_PASSWORD": password,
    }


def create_env_file(config):
    """Create or update .env file with Supabase configuration."""
    env_path = ".env"

    # Read existing .env if it exists
    existing_env = {}
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and '=' in line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    existing_env[key] = value

    # Update with new config
    existing_env.update(config)

    # Write updated .env
    with open(env_path, 'w') as f:
        f.write("# GitHub Crawler Configuration\n")
        f.write("# Generated by setup_supabase.py\n\n")

        f.write("# GitHub API\n")
        if 'GITHUB_TOKEN' not in existing_env:
            f.write("GITHUB_TOKEN=your_github_token_here\n")
        else:
            f.write(f"GITHUB_TOKEN={existing_env['GITHUB_TOKEN']}\n")
        f.write("\n")

        f.write("# Supabase Database\n")
        for key, value in config.items():
            f.write(f"{key}={value}\n")
        f.write("\n")

        f.write("# Crawler Settings\n")
        f.write("MAX_REPOS=1000\n")
        f.write("LOG_LEVEL=INFO\n")

    print(f"✅ Configuration written to {env_path}")


async def test_connection(config):
    """Test the database connection."""
    print("\n🔌 Testing database connection...")

    try:
        # Set environment variables for testing
        for key, value in config.items():
            os.environ[key] = str(value)

        async with DatabaseRepository() as db_repo:
            await db_repo.initialize_schema()
            stats = await db_repo.get_discovery_stats()

            print("✅ Database connection successful!")
            print(f"   📊 Current repositories discovered: {stats['total_discovered']:,}")
            print(f"   📈 Repositories in last 24h: {stats['discovered_last_24h']:,}")

            if stats['total_discovered'] == 0:
                print("   💡 Database is ready for first crawl run")
            else:
                print("   💡 Database has existing data - persistence is working!")

            return True

    except Exception as e:
        print(f"❌ Database connection failed: {e}")
        print()
        print("Common issues:")
        print("• Check your connection details are correct")
        print("• Ensure your IP is allowlisted in Supabase")
        print("• Verify the database exists and is accessible")
        return False


def create_github_secrets_info(config):
    """Show information about setting up GitHub secrets."""
    print("\n🔐 GitHub Actions Setup")
    print("=" * 30)
    print("Add these secrets to your GitHub repository:")
    print("(Settings → Secrets and variables → Actions → New repository secret)")
    print()

    for key, value in config.items():
        if key == "POSTGRES_PASSWORD" or "PASSWORD" in key:
            print(f"• {key}: [your password - keep this secure]")
        else:
            print(f"• {key}: {value}")

    print()
    print("Also add:")
    print("• GITHUB_TOKEN: [your GitHub personal access token]")


async def main():
    """Main setup function."""
    try:
        # Get configuration
        config = get_supabase_info()
        if not config:
            print("❌ Setup cancelled")
            return

        # Create .env file
        create_env_file(config)

        # Test connection
        connection_ok = await test_connection(config)

        if connection_ok:
            print("\n🎉 Supabase setup complete!")
            print()
            print("Next steps:")
            print("1. Update GITHUB_TOKEN in .env file")
            print("2. Test locally: python -m crawler.main --repos 100 --matrix-total 2 --matrix-index 0")
            print("3. Set up GitHub Actions with the secrets shown below")

            create_github_secrets_info(config)
        else:
            print("\n❌ Setup incomplete - fix connection issues first")

    except KeyboardInterrupt:
        print("\n❌ Setup cancelled by user")
    except Exception as e:
        print(f"\n❌ Setup error: {e}")


if __name__ == "__main__":
    asyncio.run(main())
